### ISSUE TITLE
SIP Media Application requires voice connector?

### ISSUE THREAD

**Issue by bitshop** [awsdocs/amazon-chime-administration-guide#3]
I don't see this anywhere in the docs, maybe I missed it, but spent a while trying to find why the dropbox was blank to select phone number.

This looks like a great primitive to build on, thank you.

**Comment by ColonelWilco** [comment]
Hi.
Terribly sorry for the late reply. I had a 2FA issue with GitHub that took forever to resolve. 
SIP apps require Lambda functions. You use voice connectors with existing IP enabled PBX hardware. 
For information about phone numbers, see https://docs.aws.amazon.com/chime/latest/ag/phone-numbers.html. For more about SIP apps, see https://docs.aws.amazon.com/chime/latest/dg/build-lambdas-for-sip-sdk.html, and for more about voice connectors, see https://docs.aws.amazon.com/chime/latest/ag/voice-connectors.html.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
