### ISSUE TITLE
Some `chime:AttendeeLeft` Events missing

### ISSUE THREAD

**Issue by tonydub** [awsdocs/amazon-chime-administration-guide#4]
Our video conferencing system uses the Amazon Chime SDK and uses the CreateMeeting API  to send Amazon Chime SDK meeting event notifications to one Amazon SQS queue.

The system does receive Chime events via a consumer listening to the configured SQS queue.

We have found that sometimes `chime:AttendeeLeft` events are missing, which results in not updating the presence status of some participants correctly.

Do you have any clues as to why this is happening?

Below is a sample of the PHP code used to consume the messages:

```php
$result = $this->sqsClient->receiveMessage([
    'AttributeNames' => ['SentTimestamp'],
    'MaxNumberOfMessages' => 10,
    'MessageAttributeNames' => ['All'],
    'QueueUrl' => $queueUrl, 
    'WaitTimeSeconds' => 20,
]);
if (!empty($result->get('Messages'))) {
    $messages = $result->get('Messages');

    foreach ($messages as $message) {
        yield $message;
    }
}
```

Thanks for your attention

**Comment by tonydub** [comment]
To support my point, we have to reproduce the loss of the `chime:AttendeeLeft` event when 4 browsers are closed simultaneously. We receive the event twice for the same user.

**Comment by ColonelWilco** [comment]
Hi Tony,
I'm so sorry for the late reply. I had a 2FA issue with GitHub that took forever to resolve. I've forwarded your issue to the engineers for a look, which is the best/most I can do.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
